package javaapplication2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VMH
 */

import javax.swing.Timer;
import javax.swing.JOptionPane;


public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
    }
    public static int POINT;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bird = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pipe2 = new javax.swing.JLabel();
        pipe1 = new javax.swing.JLabel();
        point_lb = new javax.swing.JLabel();
        pipe3 = new javax.swing.JLabel();
        pipe4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        bird.setIcon(new javax.swing.ImageIcon("E:\\LapTrinhNangCao\\Image\\bird.png")); // NOI18N
        jPanel1.add(bird);
        bird.setBounds(80, 140, 60, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 350, 180, 70);

        pipe2.setIcon(new javax.swing.ImageIcon("E:\\LapTrinhNangCao\\Image\\ong.png")); // NOI18N
        jPanel1.add(pipe2);
        pipe2.setBounds(610, 320, 150, 790);

        pipe1.setIcon(new javax.swing.ImageIcon("E:\\LapTrinhNangCao\\Image\\ong.png")); // NOI18N
        jPanel1.add(pipe1);
        pipe1.setBounds(220, 300, 150, 790);

        point_lb.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        point_lb.setForeground(new java.awt.Color(204, 0, 102));
        point_lb.setText("0");
        jPanel1.add(point_lb);
        point_lb.setBounds(790, 10, 90, 40);

        pipe3.setIcon(new javax.swing.ImageIcon("E:\\LapTrinhNangCao\\Image\\pipe1.jpg")); // NOI18N
        jPanel1.add(pipe3);
        pipe3.setBounds(600, -600, 160, 800);

        pipe4.setIcon(new javax.swing.ImageIcon("E:\\LapTrinhNangCao\\Image\\pipe1.jpg")); // NOI18N
        jPanel1.add(pipe4);
        pipe4.setBounds(210, -640, 160, 800);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\LapTrinhNangCao\\Image\\background.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int x = bird.getLocation().x;
        int y = bird.getLocation().y;
        if(y < 60) y = 60;
        bird.setBounds(x, y-60, bird.getSize().width, bird.getSize().height);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel1.remove(jButton1);
        jPanel1.revalidate();
        jPanel1.repaint();
        startRefreshing();
    }//GEN-LAST:event_jButton1ActionPerformed
    public Timer myTimer = null;
    protected void stopRefreshing() {
        if (myTimer != null) {
            myTimer.stop();
            myTimer = null;
        }
        /*if (pipeTimer != null) {
            pipeTimer.stop();
            pipeTimer = null;
        }*/
    }
    protected void startRefreshing() {
        stopRefreshing();
        myTimer = new Timer(15, e -> {
            runGame();
        });
        POINT = 0;
        myTimer.start();
    }
    
    void runGame(){
        int x = bird.getLocation().x;
        int y = bird.getLocation().y;
        bird.setBounds(x, y+2, bird.getSize().width, bird.getSize().height);
        
        int pipe_x1 = pipe1.getLocation().x;
        int pipe_y1 = pipe1.getLocation().y;
        if (pipe_x1 <= -65) {
            pipe_x1 = 850;
            pipe_x1 += Math.round(Math.random()*200-70);
            POINT++;
            pipe_y1 += (Math.random()*200 - 50);
            pipe_y1 += 50;
        }
        
        int pipe_x2 = pipe2.getLocation().x;
        int pipe_y2 = pipe2.getLocation().y;
        if (pipe_x2 <= -65) {
            pipe_x2 = 850;
            pipe_x2 += Math.round(Math.random()*200-70);
            POINT++;
            pipe_y2 += (Math.random()*200 - 50);
            pipe_y2 += 50;
        };
        
        int pipe_x3 = pipe3.getLocation().x;
        int pipe_y3 = pipe3.getLocation().y;
        if (pipe_x3 <= -65) {
            pipe_x3 = 850;
            pipe_x3 += Math.round(Math.random()*200-70);
            pipe_y3 += (Math.random()*200 - 50);
        }
        
        int pipe_x4 = pipe4.getLocation().x;
        int pipe_y4 = pipe4.getLocation().y;
        if (pipe_x4 <= -65) {
            pipe_x4 = 850;
            pipe_x4 += Math.round(Math.random()*200-70);
            pipe_y4 += (Math.random()*200 - 50);
        };
        
        
        String s = Integer.toString(POINT);
        point_lb.setText(s);
        
        pipe1.setBounds(pipe_x1 -= 2, pipe_y1, pipe1.getSize().width, pipe1.getSize().height);
        pipe2.setBounds(pipe_x2 -= 2, pipe_y2, pipe2.getSize().width, pipe2.getSize().height);
        pipe3.setBounds(pipe_x3 -= 2, pipe_y3, pipe3.getSize().width, pipe3.getSize().height);
        pipe4.setBounds(pipe_x4 -= 2, pipe_y4, pipe4.getSize().width, pipe4.getSize().height);
        if(y > 420){
            JOptionPane.showMessageDialog(null, "GAME OVER");
            stopRefreshing();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
                POINT = 0;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bird;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel pipe1;
    public javax.swing.JLabel pipe2;
    public javax.swing.JLabel pipe3;
    public javax.swing.JLabel pipe4;
    private javax.swing.JLabel point_lb;
    // End of variables declaration//GEN-END:variables
}
