/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hoang dep trai
 */


import javax.swing.Timer;
import javax.swing.JOptionPane;

public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bird = new javax.swing.JLabel();
        point_lb = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        pipe = new javax.swing.JLabel();
        pipe1 = new javax.swing.JLabel();
        pipe2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backgr_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        bird.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bird.png"))); // NOI18N
        jPanel1.add(bird);
        bird.setBounds(60, 250, 60, 40);

        point_lb.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        point_lb.setForeground(new java.awt.Color(255, 0, 0));
        point_lb.setText("0");
        jPanel1.add(point_lb);
        point_lb.setBounds(700, 10, 160, 70);
        point_lb.getAccessibleContext().setAccessibleName("");

        btn_start.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        btn_start.setForeground(new java.awt.Color(255, 0, 0));
        btn_start.setLabel("START");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        jPanel1.add(btn_start);
        btn_start.setBounds(300, 210, 210, 60);
        btn_start.getAccessibleContext().setAccessibleName("");

        pipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pipe1.jpg"))); // NOI18N
        jPanel1.add(pipe);
        pipe.setBounds(110, -700, 140, 830);

        pipe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pipe1.jpg"))); // NOI18N
        jPanel1.add(pipe1);
        pipe1.setBounds(410, -640, 150, 800);

        pipe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pipe1.jpg"))); // NOI18N
        jPanel1.add(pipe2);
        pipe2.setBounds(670, -670, 140, 793);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ong.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 380, 138, 790);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ong.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 330, 138, 790);

        backgr_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        backgr_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgr_labelMouseClicked(evt);
            }
        });
        jPanel1.add(backgr_label);
        backgr_label.setBounds(0, 0, 860, 460);
        backgr_label.getAccessibleContext().setAccessibleName("backgr_label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static int run = 0;
    
  
    /*TimerTask task = new TimerTask(){
        public void run(){
            if(run == 1){
                int x = bird.getLocation().x;
                int y = bird.getLocation().y;
                bird.setBounds(x, y+=5, 110, 80); 
            }            
        }
    };*/
    
  
    
    /*Timer myTimer = new Timer(100, new ActionListener(){
        
    });*/
    
    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        jPanel1.remove(btn_start);
        jPanel1.revalidate();
        jPanel1.repaint(); 
        run = 1;
        /*for(int i = 0; i < 10; i++){
            int x = bird.getLocation().x;
            int y = bird.getLocation().y;
            bird.setBounds(x, y+=5, 110, 80);            
        }*/
        startRefreshing();
    }//GEN-LAST:event_btn_startActionPerformed

    private void backgr_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgr_labelMouseClicked
        int x = bird.getLocation().x;
        int y = bird.getLocation().y;
        if(y < 50)y=50;
        bird.setBounds(x, y-=50, 61, 46);        // TODO add your handling code here:
        //run = 3;
        
    }//GEN-LAST:event_backgr_labelMouseClicked
    int POINT;
    public void runGame(){
        String s = Integer.toString(POINT);
        point_lb.setText(s);
        int x = bird.getLocation().x;
        int y = bird.getLocation().y;
        /*if(run < 0){
            y -= 20;
            run++;
        }else{
            y += 2;
        }*/
        bird.setBounds(x, y+2, bird.getSize().width, bird.getSize().height); 
        
        int pipe_x = pipe.getLocation().x;
        int pipe_y = pipe.getLocation().y;
        if (pipe_x <= -30) {
            pipe_x = 850;
            pipe_x += Math.round(Math.random()*200-70);
            POINT++;
            pipe_y += (Math.random()*200 - 50);
        }
        
        int pipe_x1 = pipe1.getLocation().x;
        int pipe_y1 = pipe1.getLocation().y;
        if (pipe_x1 <= -30) {
            pipe_x1 = 850;
            pipe_x1 += Math.round(Math.random()*200-70);
            POINT++;
            pipe_y1 += (Math.random()*200 - 50);
        }
        
        int pipe_x2 = pipe2.getLocation().x;
        int pipe_y2 = pipe2.getLocation().y;
        if (pipe_x2 <= -30) {
            pipe_x2 = 850;
            pipe_x2 += Math.round(Math.random()*200-70);
            POINT++;
            pipe_y2 += (Math.random()*200 - 50);
        };
        
        int pipe_x4 = jLabel2.getLocation().x;
        int pipe_y4 = jLabel2.getLocation().y;
        
       
        int pipe_x6 = jLabel4.getLocation().x;
        int pipe_y6 = jLabel4.getLocation().y;
        
        if(pipe_x4 <= -30){
            pipe_x4 = 850;
            pipe_x4 += Math.round(Math.random()*200-70);
            //POINT++;
            pipe_y4 += (Math.random()*200 - 100);
        }
        
        if(pipe_x6 <= -30){
            pipe_x6 = 850;
            pipe_x6 += Math.round(Math.random()*200-70);
            //POINT++;
            pipe_y6 += (Math.random()*200 - 100);
        }
        
        pipe.setBounds(pipe_x -= 2, pipe_y, pipe.getSize().width, pipe.getSize().height);
        pipe1.setBounds(pipe_x1 -= 2, pipe_y1, pipe1.getSize().width, pipe1.getSize().height);
        pipe2.setBounds(pipe_x2 -= 2, pipe_y2, pipe2.getSize().width, pipe2.getSize().height);
        jLabel2.setBounds(pipe_x4 -= 2, pipe_y4, jLabel2.getSize().width, jLabel2.getSize().height);
        jLabel4.setBounds(pipe_x6 -= 2, pipe_y6, jLabel4.getSize().width, jLabel4.getSize().height);
        
        if(y+5 >= 410) {
            JOptionPane.showMessageDialog(null, "GAME OVER");
            stopRefreshing();
        }
    }
    
    public Timer myTimer = null;
    protected void stopRefreshing() {
        if (myTimer != null) {
            myTimer.stop();
            myTimer = null;
        }
        /*if (pipeTimer != null) {
            pipeTimer.stop();
            pipeTimer = null;
        }*/
    }
    protected void startRefreshing() {
        stopRefreshing();
        myTimer = new Timer(15, e -> {
            runGame();
        });
        POINT = 0;
        myTimer.start();
    }
    
    /*
    
    public Timer pipeTimer = null;
    protected void pipStartRefreshing(){
        stopRefreshing();
        pipeTimer = new Timer(20, e -> {
        
        });
        pipeTimer.start();
    }
    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                run = 0;
                new Frame2().setVisible(true);    
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgr_label;
    public static javax.swing.JLabel bird;
    public static javax.swing.JButton btn_start;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel pipe;
    public javax.swing.JLabel pipe1;
    public javax.swing.JLabel pipe2;
    public javax.swing.JLabel point_lb;
    // End of variables declaration//GEN-END:variables
}
